### ISSUE TITLE
Allow adding array of native datatypes

### ISSUE THREAD

**Issue by paivinayak187** [pgroot/express-swagger-generator#24]
Could we get a support to add array of native datatypes? Like one below
@Property {string[]}
@Property {object[]}
@Property {integer[]}
@Property {boolean[]}

**Comment by caiomajdalani** [comment]
Same problem here. 
I think the problem is that the logic to discover if is a array of primitive types (string, etc), is a "if" on line 103 of swagger.js that is unreachable: 

`function parseItems(obj) {
    if (obj.applications && obj.applications.length > 0 && obj.applications[0].name) {
        const type = obj.applications[0].name;
        **if (type == 'object' || type == 'string' || type == 'integer' || type == 'boolean') {
            return { "type": type }
        }**
        else return { "$ref": "#/definitions/" + type };
    }
    else return undefined;
}`

This function is only called by "function parseTypedef" that is called by this guy on line 248:

`if (comments[i].length > 0 && comments[i][0]['title'] && comments[i][0]['title'] == 'typedef') {

                const typedefParsed = parseTypedef(comments[i]);
                definitions[typedefParsed.typeName] = typedefParsed.details;
                continue;
            }` 

So, my conclusion is that is impossible to use a Array of primitive types. Only of custom types (typeDef).

Can it be reviewed please? Thanks!!
